/*
 * File: app/view/CategoriesTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CategoriesTabPanel', {
    extend: 'Ext.tab.Panel',

    requires: [
        'MyApp.view.PeopleContainer',
        'MyApp.view.OrganizationsContainer',
        'MyApp.view.OthersContainer',
        'MyApp.view.HistoryContainer'
    ],

    config: {
        items: [
            {
                xtype: 'peopleContainer',
                title: 'Хора',
                iconCls: 'team'
            },
            {
                xtype: 'organizationsContainer',
                title: 'Организации',
                iconCls: 'favorites'
            },
            {
                xtype: 'othersContainer',
                title: 'Други',
                iconCls: 'info'
            },
            {
                xtype: 'historyContainer',
                title: 'История',
                iconCls: 'bookmarks'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});