/*
 * File: app/view/DetailsContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DetailsContainer', {
    extend: 'Ext.Container',
    alias: 'widget.detailsContainer',

    config: {
        cls: 'app-page',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype:  'container',
                docked: 'bottom',
                cls: 'app-actions',
                items: [
                    {
                        xtype: 'button',
                        cls: 'app-button',
                        action: 'sendSms',
                        text: 'Send SMS'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
            var backButton = Ext.ComponentQuery.query('mainView toolbar button[action=backButton]')[0],
            facebookSharebutton = Ext.ComponentQuery.query('mainView toolbar button[action=facebookShareButton]')[0];

        this.on('show', function () {
            backButton.show();
            facebookSharebutton.show();
        });
        this.on('hide',function(){
             backButton.hide();
            facebookSharebutton.hide();
        });

        this.template = new Ext.Template(       
        '<div name="{id}" class="details-container">',
            '<div class="details-img">',
                '<img src={bigImageUrl} alt="no image"></img>',
            '</div>',
            '<div class="details-header">',
                '<time>',
                    '<small>Стартирала на</small>',
                    '<strong>{date}</strong>',
                '</time>',
                '<div class="required-amount">',
                    '<small>Необходима сума</small>',
                    '<strong>{sum}</strong>',
                '</div>',
            '</div>',
            '<div class="description-container">',
                '<h1>{title}</h1>',
                '<p class="info-sms">',
                    '<small>Изпратете дарителски SMS с текст на латиница <strong>{text}</strong> на номер <strong>17 777</strong> (за абонати на GLOBUL, VIVACOM и Mtel)</small>',
                '</p>',
                '<p class="description">',
                    '{description}',
                    '<br><a href="{campaignUrl}" target="_blank" class="read-more">Прочети повече</a>',
                '</p>',
                '<p class="info-campaign first-child">',
                    '<small><strong>За абонати по договор с GLOBUL, VIVACOM и Mtel цената на 1 sms е 1 лв. За потребители на предплатени услуги на трите мобилни оператори цената на 1 sms е 1,20 лв. с ДДС.</strong></small>',
                '</p>',
                '<p class="info-campaign">',
                    '<small>Избраната от вас кампания получава минимум 90% от всички финансови постъпления, а останалата сума покрива административни разходи по проекта DMS и невзетите плащания от страна на операторите. Повече информация можете да намерите <a href="http://dmsbg.com/index.php?page=1" target="_blank"><strong>тук</strong></a>.</small>',
                '</p>',
                '<p class="info-campaign">',
                    '<small>Информация за набраните смс-и може да намeрите <a href="http://dmsbg.com/index.php?page=2" target="_blank"><strong>тук</strong></a>.</small>',
                '</p>',
            '</div>',
        '</div>',
        // a configuration object:
        {
            compiled: true      // compile immediately
        }
        );
    }

});