/*
 * File: app/view/DetailsContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DetailsContainer', {
    extend: 'Ext.Container',
    alias: 'widget.detailsContainer',

    config: {
        cls: 'app-page',
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        items: [
            {
                xtype:  'container',
                docked: 'bottom',
                cls: 'app-actions',
                items: [
                    {
                        xtype: 'button',
                        cls: 'app-button',
                        action: 'sendSms',
                        text: 'Send SMS'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.template = new Ext.Template(       
        '<div name="{id}" class="details-container">',
            '<div class="details-img">',
                '<img src={bigImageUrl} alt="no image"></img>',
            '</div>',
            '<div class="details-header">',
                '<time>',
                    '<small>Стартирала на</small>',
                    '<strong>{date}</strong>',
                '</time>',
                '<div class="required-amount">',
                    '<small>Необходима сума</small>',
                    '<strong>{sum}</strong>',
                '</div>',
            '</div>',
            '<div class="description">',
                '<h1>{title}</h1>',
                '<p>{description}</p>',
            '</div>',
        '</div>',
        // a configuration object:
        {
            compiled: true      // compile immediately
        }
        );
    }

});