/*
 * File: app/view/DetailsContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DetailsContainer', {
    extend: 'Ext.Container',
    alias: 'widget.detailsContainer',

    config: {
        items: [
            {
                xtype: 'button',
                action: 'sendSms',
                docked: 'bottom',
                text: 'Send SMS'
            }
        ]
    },

    initialize: function() {
        this.callParent();
        this.template = new Ext.Template(       
        '<div name="{id}">',
        '<img src={bigImageUrl} width="100" height="100" alt="no image"></img>',
        '<h1>{title}</h1>',
        '<p>{description}</p>',
        '<time>{date}</time>',
        '</div>',
        // a configuration object:
        {
            compiled: true      // compile immediately
        }
        );
    }

});