/*
 * File: app/view/DetailsContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SearchContainer', {
 
    extend: 'Ext.form.Panel',
    alias: 'widget.searchContainer',
 
    config: {
        height: '35%',
        itemId: 'searchContainer',
        left: '5%',
        padding: 10,
        top: '0%',
        width: '40%',
        hideOnMaskTap: true,
        modal: true,
        items: [
                {
                    xtype: 'textfield',
                    label: 'Keyword',
                    name:'keyword'
                },
            {
                xtype: 'checkboxfield',
                name : 'organizations',
                label: 'Организации',
                value: '1',
                checked: true
            },
            {
                xtype: 'checkboxfield',
                name : 'people',
                label: 'Хора',
                value: '0'
            },
            {
                xtype: 'checkboxfield',
                name : 'others',
                label: 'Други',
                value:'2'
            },
            {
                xtype:'button',
                text:'Search'
            }
        ]
    }
});