/*
 * File: app/controller/PeopleController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.PeopleController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            peopleList: 'peopleContainer list',
            tabPanel: 'peopleContainer tabpanel',
            detailsContainer: 'peopleContainer container[title=details]'
        },

        control: {
            "peopleList": {
                itemtap: 'onContainerItemTap'
            },
            "detailsContainer": {
                initialize: 'onContainerInitialize'
            }
        }
    },

    onContainerItemTap: function(thisObj, index, target, record, e, eOpts) {
        var tabPanel = this.getTabPanel();

        tabPanel.setActiveItem(1);
        console.log(this.getDetailsContainer().element);
        window.el = this.getDetailsContainer().element;

        this.getDetailsContainer().element.on(
        { 
            swipe: function (e) {
                console.log(e);
                if(e.direction === "right") {
                    tabPanel.setActiveItem(0);
                }

            } 
        });
    },

    onContainerInitialize: function(target) {
        console.log('details is initialized');
    }

});