/*
 * File: app/controller/PeopleController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.PeopleController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            peopleList: 'peopleContainer list',
            tabPanel: 'peopleContainer tabpanel',
            detailsContainer: 'peopleContainer container[title=details]',
            sendSmsButton: 'detailsContainer button[action=sendSMS]'
        },

        control: {
            "peopleList": {
                itemtap: 'onContainerItemTap'
            },
            "peopleContainer container[title=details] button[action=sendSMS]": {
                tap: 'onSmsButtonTap'
            }
        }
    },

    onContainerItemTap: function(thisObj, index, target, record, e, eOpts) {
        var tabPanel = this.getTabPanel();

        tabPanel.setActiveItem(1);
        console.log(this.getDetailsContainer().element);
        window.el = this.getDetailsContainer().element;

    },

    onSmsButtonTap: function(button, e, eOpts) {

    },

    launch: function() {
        var me = this;

        me.getDetailsContainer().element.on(
        { 
            swipe: function (e) {
                me.getTabPanel().setActiveItem(0);  
            } 
        });
    }

});